In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as st
import os
import csv
from pathlib import Path

stroke_data_to_load = Path("../Resources/healthcare-dataset-stroke-data.csv")

# Read in the data. 
stroke_data_df = pd.read_csv(stroke_data_to_load)
stroke_data_df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [11]:
#  Create new data frame.
new_stroke_data_df = stroke_data_df.drop(columns=['ever_married', 'work_type', 'avg_glucose_level'])
new_stroke_data_df.dropna(inplace=True)
new_stroke_data_df.head()

,id,gender,age,hypertension,heart_disease,Residence_type,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Urban,36.6,formerly smoked,1
2,31112,Male,80.0,0,1,Rural,32.5,never smoked,1
3,60182,Female,49.0,0,0,Urban,34.4,smokes,1
4,1665,Female,79.0,1,0,Rural,24.0,never smoked,1
5,56669,Male,81.0,0,0,Urban,29.0,formerly smoked,1

In [13]:
# Update column names

new_stroke_data_df.rename(columns={'id': 'ID', 'gender': 'Gender', 'age': 'Age', 
                               'hypertension': 'Hypertension', 'heart_disease': 'Heart Disease',
                               'Residence_type': 'Residence Type', 'bmi': 'BMI',
                               'smoking_status': 'Smoking Status', 'stroke': 'Stroke'})

#new_stroke_data_df=  new_stroke_data_df.astype({"Age": int}, errors='raise')

,ID,Gender,Age,Hypertension,Heart Disease,Residence Type,BMI,Smoking Status,Stroke
0,9046,Male,67.0,0,1,Urban,36.6,formerly smoked,1
2,31112,Male,80.0,0,1,Rural,32.5,never smoked,1
3,60182,Female,49.0,0,0,Urban,34.4,smokes,1
4,1665,Female,79.0,1,0,Rural,24.0,never smoked,1
5,56669,Male,81.0,0,0,Urban,29.0,formerly smoked,1
...,...,...,...,...,...,...,...,...,...
5104,14180,Female,13.0,0,0,Rural,18.6,Unknown,0
5106,44873,Female,81.0,0,0,Urban,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Rural,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Rural,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Urban,26.2,Unknown,0

Elona
#Question 1:Is there a correlation between obesity (high BMI) and the likelihood of experiencing a stroke? 

Chart 1 - Histogram of bins by BMI - Patient had a stroke
Chart 2 - Histogram of bins by BMI - Patients who DID NOT have a stroke
Chart 3- Line graph for total number of stroke patients across all BMIs

Limitation:
    BMI by height -- no height data

Kelly

Question 2: Does a person’s residency type increase the risk of having a stroke? Are individuals that live in Urban settings more likely to have a stroke vs. those that live in a Rural setting?

Chart 1 - Pie Chart
Compare patients who had a stroke between Urban vs. Rural residencies

Chart 2 - Statistical graph on rural population?

Aisha

Question 3: Are males over 60 at a higher risk of having a stroke compared to males 20-59?
Part 2: Does smoking status (current smoker) have an impact on the likelihood of stroke for both populations?

    Chart 1: Pie Chart -- Males over 60 who have had a stroke vs males 20-59 who have had a stroke, to show %
    Chart 2: Line Chart -- smokers vs non-smokers for both age ranges

Raje
Question 4.	Are patients with hypertension vs patients with heart disease more likely to have a stroke?
    Chart 1: Bar Chart for comparison of hypertension vs heart disease patients who had a stroke 
    Chart 2: Pie Chart - Percentage of those with hypertension, percentage of those with heart disease